#!/bin/zsh

log () {
  tput setaf 2; echo -e "\n$1\n"; tput sgr0
}


ssh marcelrobitaille.me "rm -rf startpage"

log "Running build"
gulp build | sed 's/^/  /'


log "Copying files"
cd build
rsync -a ./ marcel@marcelrobitaille.me:~/startpage | sed 's/^/  /'

